# Generated by Django 3.0 on 2021-06-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor_info',
        ),
    ]
